; development version for pytest
[pytest]
addopts = --timeout=60 -m 'not slow' --ignore lib --ignore lib64
; coverage disabled by default as it's become really slow and drags down unit tests
; --cov=src --cov-report=html
markers = slow: This is a non-unit test and thus is not run by default. Use ``-m slow`` to run these, or ``-m 1`` to run all tests.
junit_family = legacy
consider_namespace_packages = true

filterwarnings =
   ; Keycloak uses untrusted SSL cert in dev
   ignore:Unverified HTTPS request is being made to host \'auth

   ; post python 3.14
   ignore:Deprecated call to `pkg_resources.declare_namespace\(

   ; also see DIR-873
   ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning
   ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated and scheduled for removal

   ; setuptools >= 81
   ignore:pkg_resources is deprecated as an API.

   ; sqlalchemy
   ignore: The Query.get\(\) method is considered legacy
   ignore: Object of type <.*> not in session, add operation along

   ; pyramid
   ignore:Authentication and authorization policies have been deprecated in favor of security policies.
   ignore:The new security policy has deprecated unauthenticated_userid.
